# Generated by Django 3.0.7 on 2024-07-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='paid_date',
            field=models.DateField(auto_now=True),
        ),
    ]
