# Generated by Django 3.0.7 on 2024-07-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payroll_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='paid_date',
            field=models.DateField(),
        ),
    ]
