# Generated by Django 3.0.7 on 2024-07-25 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptReport',
            fields=[
                ('receipt_no', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SALE', 'Sale'), ('SP', 'Service Provided'), ('OT', 'Other')], default='SALE', max_length=25)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('paid_by', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('date', models.DateTimeField()),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
