# Generated by Django 3.0.7 on 2024-07-25 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_auto_20240725_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('receipt_no', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SALE', 'Sale'), ('SP', 'Service Provided'), ('OT', 'Other')], default='SALE', max_length=25)),
                ('remarks', models.TextField(blank=True, max_length=255, null=True)),
                ('paid_by', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('date', models.DateTimeField()),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiptreport', to='report.Report')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RenameModel(
            old_name='PaymentReport',
            new_name='Payment',
        ),
        migrations.DeleteModel(
            name='ReceiptReport',
        ),
    ]
