# Generated by Django 3.0.7 on 2024-07-26 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20240726_1344'),
        ('transactions', '0017_auto_20240724_1420'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0006_auto_20240726_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Payroll'),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchasebill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.PurchaseBillDetails'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='prepared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
