# Generated by Django 3.0.7 on 2024-07-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20240726_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], default='EXPENSE', max_length=25),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('SERVICE PROVIDED', 'Service Provided'), ('OTHER', 'Other')], default='SALE', max_length=25),
        ),
    ]
