# Generated by Django 3.0.7 on 2024-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20240728_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('SERVICE PROVIDED', 'Service Provided'), ('DUE', 'Due'), ('OTHER', 'Other')], default='SALE', max_length=25),
        ),
    ]
