# Generated by Django 3.0.7 on 2024-08-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20240728_1423'),
        ('transactions', '0019_auto_20240729_1714'),
        ('report', '0011_auto_20240801_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Payroll'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purchasebill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.PurchaseBillDetails'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='salebill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.SaleBillDetails'),
        ),
    ]
