# Generated by Django 3.0.7 on 2024-08-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20240806_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eway', models.CharField(blank=True, max_length=50, null=True)),
                ('veh', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('po', models.CharField(blank=True, max_length=50, null=True)),
                ('cgst', models.FloatField(default=0.0, null=True)),
                ('sgst', models.FloatField(default=0.0, null=True)),
                ('igst', models.FloatField(default=0.0, null=True)),
                ('cess', models.FloatField(default=0.0, null=True)),
                ('tcs', models.FloatField(default=0.0, null=True)),
                ('discount_percentage', models.SmallIntegerField(default=0, null=True)),
                ('discount_amount', models.FloatField(default=0.0, null=True)),
                ('total', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('due_amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplierreport',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='report',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='report',
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='SupplierReport',
        ),
        migrations.AddField(
            model_name='receiptbill',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='report.Receipt'),
        ),
    ]
