# Generated by Django 3.0.7 on 2024-08-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0016_receipt_vat_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptbill',
            name='discount_percentage',
        ),
    ]
