# Generated by Django 3.0.7 on 2024-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20240724_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='placed_at',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
