# Generated by Django 3.0.7 on 2024-08-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('kg', 'KILOGRAM'), ('ltr', 'LITRE'), ('pc', 'PIECE')], default='pc', max_length=10),
        ),
    ]
