# Generated by Django 3.0.7 on 2024-08-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20240812_1514'),
        ('inventory', '0009_auto_20240805_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Branch'),
        ),
    ]
