# Generated by Django 3.0.7 on 2024-08-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stocktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='placed_at',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
