# Generated by Django 3.0.7 on 2024-07-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='cess',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='cgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='igst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='sgst',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='tcs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
