# Generated by Django 3.0.7 on 2024-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20240707_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='total',
            field=models.FloatField(),
        ),
    ]
