# Generated by Django 3.0.7 on 2024-07-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20240707_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
