# Generated by Django 3.0.7 on 2024-07-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20240707_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='cess',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='cgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='igst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='sgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='tcs',
            field=models.FloatField(default=0.0),
        ),
    ]
