# Generated by Django 3.0.7 on 2024-07-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20240707_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebilldetails',
            name='cess',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salebilldetails',
            name='cgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salebilldetails',
            name='igst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salebilldetails',
            name='sgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salebilldetails',
            name='tcs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='salebilldetails',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
