# Generated by Django 4.2.3 on 2024-07-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20240707_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='gstin',
            field=models.IntegerField(max_length=9),
        ),
    ]
