# Generated by Django 3.0.7 on 2024-07-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_salebill_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='gstin',
            field=models.CharField(max_length=9),
        ),
    ]
