# Generated by Django 3.0.7 on 2024-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20240717_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='discount',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
