# Generated by Django 3.0.7 on 2024-07-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_purchasebilldetails_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebilldetails',
            old_name='discount',
            new_name='discount_percentage',
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='discount_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
