# Generated by Django 3.0.7 on 2024-07-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20240717_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebilldetails',
            name='due_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchasebilldetails',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salebilldetails',
            name='due_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salebilldetails',
            name='paid_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
