# Generated by Django 3.0.7 on 2024-07-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20240718_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='cess',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
