# Generated by Django 3.0.7 on 2024-07-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_auto_20240718_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebilldetails',
            name='discount_amount',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
