# Generated by Django 3.0.7 on 2024-07-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20240718_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebilldetails',
            name='cess',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
