# Generated by Django 3.0.7 on 2024-07-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20240718_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='gstin',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
