# Generated by Django 3.0.7 on 2024-07-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20240724_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebilldetails',
            name='discount_amount',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='salebilldetails',
            name='discount_percentage',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
