# Generated by Django 3.0.7 on 2024-08-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20240729_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebill',
            name='gstin',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
