# Generated by Django 3.0.7 on 2024-08-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20240805_1631'),
        ('transactions', '0021_auto_20240806_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Stock'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Stock'),
        ),
    ]
