# Generated by Django 3.0.7 on 2024-08-09 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20240805_1631'),
        ('transactions', '0022_auto_20240809_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitem', to='inventory.Stock'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleitem', to='inventory.Stock'),
        ),
    ]
