# Generated by Django 3.0.7 on 2024-08-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_auto_20240809_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebilldetails',
            old_name='tcs',
            new_name='tds',
        ),
        migrations.RenameField(
            model_name='salebilldetails',
            old_name='tcs',
            new_name='tds',
        ),
    ]
