# Generated by Django 3.0.7 on 2024-08-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20240809_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salebill',
            old_name='gstin',
            new_name='vat_no',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='gstin',
            new_name='vat_no',
        ),
    ]
