# Generated by Django 3.0.7 on 2024-08-13 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20240812_1514'),
        ('transactions', '0025_auto_20240809_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Branch'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.Branch'),
        ),
    ]
