# Generated by Django 3.0.7 on 2024-08-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20240812_1514'),
        ('homepage', '0002_auto_20240812_0907'),
    ]

    operations = [
    ]
